using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

// PortableKnowledge Logging Framework for .NET
// (C) Portable Knowledge, LLC
//
// Released to the public under the Portable Knowledge Open Source Component License
//
// Permission is hereby granted, free of charge, to any person or organization obtaining a 
// copy of the software and accompanying documentation covered by this license (the "Software")
// to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare 
// derivative works of the Software, and to permit third-parties to whom the Software is 
// furnished to do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including the above license
// grant, this restriction and the following disclaimer, must be included in all copies of the 
// Software, in whole or in part, and all derivative works of the Software, unless such copies 
// or derivative works are solely in the form of machine-executable object code generated by 
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
// PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE 
// DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
// OTHER DEALINGS IN THE SOFTWARE.  IN NO CASE DOES THE USE OF THIS SOFTWARE EXPRES OR IMPLY 
// ANY PARTNERSHIP OR COOPERATION WITH THE AUTHORS OR COPYRIGHT HOLDERS OF THIS SOFTWARE.

namespace PortableKnowledge.Logging
{
    /// <summary>
    /// LogListener which shows logging messages in a new MessageBox.  The body of the MessageBox contains
    /// the log message, the caption lists the log level.  The only button on the MessageBox is "OK"
    /// The MessageBox guarenteed to be executed on the main application thread.
    /// </summary>
    public class MessageBoxLogListener : LogListener
    {
        /// <summary>
        /// Windows form in which to display the MessageBox
        /// </summary>
        private Form _parentForm;

        /// <summary>
        /// Initialize a new MessageBoxLogListener
        /// </summary>
        /// <param name="log">Log instance to register this listener with</param>
        /// <param name="MessageBoxParent">The Form on which the MessageBox should be modally displayed.  Must NOT be NULL.</param>
        public MessageBoxLogListener(Log log, Form MessageBoxParent)
            : base(log)
        {
            if (MessageBoxParent == null)
                throw new Exception("MessageBoxLogListener's MessageBoxParent must not be NULL");
            _parentForm = MessageBoxParent;
        }

        delegate void ShowMessageDelegate(String Message, String Title);
        private void ShowMessage(String Message, String Title)
        {
            if (this._parentForm.InvokeRequired)
            {
                ShowMessageDelegate update = new ShowMessageDelegate(ShowMessage);
                this._parentForm.Invoke(update, Message, Title);
            }
            else
            {
                MessageBox.Show(_parentForm, Message, Title, MessageBoxButtons.OK);
            }
        }

        /// <summary>
        /// Called whenever a new item is added to the registered log.  Adds the LogItem
        /// to the assocaited ListBox control.
        /// </summary>
        /// <param name="item">Details of newly-added log item</param>
        public override void ProcessLogMessage(LogItem item)
        {
            this.ShowMessage(item.ToString(" "), item.Level.ToString());
        }
    }
}
